name: metaone_wallet_sdk_example
description: Demonstrates how to use the metaone_wallet_sdk plugin.
version: 0.1.4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  provider: ^6.0.1
  shared_preferences: ^2.0.13
  metaone_wallet_sdk: ^2.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - .env
